# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(484, 434)
        self.btn_push_file = QtWidgets.QPushButton(Form)
        self.btn_push_file.setGeometry(QtCore.QRect(30, 130, 75, 23))
        self.btn_push_file.setObjectName("btn_push_file")
        self.btn_play_music = QtWidgets.QPushButton(Form)
        self.btn_play_music.setGeometry(QtCore.QRect(30, 180, 75, 23))
        self.btn_play_music.setObjectName("btn_play_music")
        self.btn_del_file = QtWidgets.QPushButton(Form)
        self.btn_del_file.setGeometry(QtCore.QRect(30, 230, 75, 23))
        self.btn_del_file.setObjectName("btn_del_file")
        self.btn_push_file_2 = QtWidgets.QPushButton(Form)
        self.btn_push_file_2.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.btn_push_file_2.setObjectName("btn_push_file_2")
        self.fileT = QtWidgets.QTextBrowser(Form)
        self.fileT.setGeometry(QtCore.QRect(120, 10, 331, 31))
        self.fileT.setObjectName("fileT")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_push_file.setText(_translate("Form", "推送音频"))
        self.btn_play_music.setText(_translate("Form", "播放音频"))
        self.btn_del_file.setText(_translate("Form", "删除音频"))
        self.btn_push_file_2.setText(_translate("Form", "Load FW File"))


class MyWindow(QtWidgets.QWidget, Ui_Form):
    def __init__(self, parent=None):
        super(MyWindow, self).__init__()
        self.fileName =''
        self.setupUi(self)
        self.btn_push_file_2.clicked.connect(self.msg)

    def msg(self, Filepath):
        directory = QtWidgets.QFileDialog.getOpenFileName(self, "选取文件", "./", "*.mp3")
        print('hh ：', directory)
        fileName = directory[0]
        self.fileT.setText(fileName)

    def connectPushFile(self,func):
        self.btn_push_file.clicked.connect(func)

    def getFileName(self):
        return  self.fileName

